global_costmap:
  # With static map 
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: true
  transform_tolerance: 0.5

  inflation_layer:
    cost_scaling_factor: 2.0
    inflation_radius: 0.1