controller_frequency: 5.0

# TrajectoryPlannerROS:
#   max_vel_x: 0.5
#   min_vel_x: 0.0

#   max_vel_theta: 8.0
#   min_in_place_vel_theta: 0.5

#   acc_lim_x: 0.8
#   acc_lim_theta: 3.0
#   holonomic_robot: false

#   # Trajectory scoring parameters
#   meter_scoring: true

#   controller_frequency: 5.0

DWAPlannerROS:
  #default 2.5 -> with this value the robot sometimes gets to close to the wall when leaving a goal position in narrow corridors, causing dwa planner to have problems
  acc_lim_x: 0.8
  
  acc_lim_y: 0.0
  
  #default 3.2
  acc_lim_th: 3.0
  
  min_vel_y: 0.0
  max_vel_y: 0.0
  max_rot_vel: 8.0
  min_rot_vel: 0.5

  yaw_goal_tolerance: 0.1
  
  #default:0.1 -> with this value the robot sometimes has troubles achieving the goal, due to low tolerance
  xy_goal_tolerance: 0.3
  
  
  # if the robot ever reaches the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so.
  latch_xy_goal_tolerance: true
 

  sim_time: 1.7
  

#cost =  path_distance_bias * (distance to path from the endpoint of the trajectory in meters)  + goal_distance_bias * (distance to local goal from the endpoint of the trajectory in meters)  + occdist_scale * (maximum obstacle cost along the trajectory in obstacle cost (0-254))
  path_distance_bias: 5.0 #default:32
  goal_distance_bias: 9.0 #default:24
  occdist_scale: 0.01 #default:0.01

  
  oscillation_reset_dist: 0.05


  prune_plan: true

  holonomic_robot: false
